version: '3.5'
services:
  node:
    #image: node:16.18.1-alpine3.16
    build: 
      context: alpine_npm/.
    #restart: always
    working_dir: /var/www/product
    stdin_open: true
    tty: true
    dns:
      - 8.8.8.8
    #environment:
    #  - NODE_ENV=production
    volumes:
      - ./web:/var/www
    #expose:
    #  - "8081"
    #command: 
    #  - 'npm install'
    #  - 'npm run dev'
    #'npm run test'
    #  - 'npm start'