FROM php:8.1-fpm

ARG USER
ARG UID
ARG GID
#ENV user=${USER}

RUN apt update && apt install -y --no-install-recommends \
    build-essential \
    libpng-dev \
    libzip-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    procps \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    net-tools \
    curl

RUN docker-php-ext-install gd pdo_mysql mysqli zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
&& chmod +x /usr/local/bin/ 

RUN apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN groupadd -g $GID $USER \
&& useradd -s /bin/bash -M -u $UID -g $USER $USER \
&& usermod -aG www-data $USER

#USER $USER